# 配置详情请参考：https://docs.halo.run/zh/developer-guide/theme/config-files
genernal:
  label: 基本设置
  items:
    access_key:
      name: access_key
      label: AccessKey <必填>
      type: text
      default: "wik"
      placeholder: "请务必与后台中的Key一致"
      description: "Access Key 用于页面中 Content API 的校验，不填会导致接口报错，默认为wik，但可以自己定义，请不要填写中文或特殊字符（请务必同时配置此处的 Access Key 和后台管理中的 Access Key，并保持一致）"
    index_title:
      name: index_title
      label: 首页标题
      type: textarea
      default: '青松'
    index_notice:
      name: index_notice
      label: 首页标题
      type: textarea
      default: '努力做有价值的技术文章'
    travle_title:
      name: travle_title           
      label: 旅行
      type: text 
      default: '生活太匆碌，美景无心顾，来一场不一样的旅行吧。迎接你的或许是阳光温暖，清风徐徐，也不一定，感受才是灵魂的语言，文字只是表达感受的标点和符号'
social:
  label: 社交网络
  items:
    github:
      name: github
      label: Github
      type: text
      placeholder: "GitHub"
      description: "https://github.com/luokangyuan"
    mail:
      name: mail
      label: 邮箱
      type: text
      placeholder: "邮箱"
      description: "邮箱地址"
    zhihu:
      name: zhihu
      label: 知乎
      type: text
      placeholder: "知乎"
      description: "知乎个人主页地址" 
    weibo:
      name: weibo
      label: 微博
      type: text
      placeholder: "微博"
      description: "微博个人主页地址"